#!/bin/bash
# GhostBot Gemini CLI agent entrypoint.
#
# Required env:
#   GH_TOKEN         GitHub PAT
#   GH_REPO          owner/repo
#   GH_BRANCH        new branch
#   BASE_BRANCH      fork from (default: main)
#   PROMPT           user's request
#   GEMINI_API_KEY   Google AI Studio API key
#
# Optional:
#   MODEL            default: gemini-2.5-pro
#   COMMIT_MESSAGE   override commit message

set -euo pipefail

log() { echo "[gemini-agent] $*"; }

require_env() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    log "ERROR: required env var $var is not set"
    exit 2
  fi
}

require_env GH_TOKEN
require_env GH_REPO
require_env GH_BRANCH
require_env PROMPT
require_env GEMINI_API_KEY

BASE_BRANCH="${BASE_BRANCH:-main}"
MODEL="${MODEL:-gemini-2.5-pro}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Agent: ${PROMPT:0:60}}"

REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${GH_REPO}.git"

log "repo=${GH_REPO} base=${BASE_BRANCH} branch=${GH_BRANCH} model=${MODEL}"

log "cloning..."
git clone --depth 50 --branch "${BASE_BRANCH}" "${REPO_URL}" /workspace/repo
cd /workspace/repo
git checkout -b "${GH_BRANCH}"

export GEMINI_API_KEY

log "running Gemini CLI..."
# gemini --prompt = non-interactive one-shot
gemini \
  --model "${MODEL}" \
  --yolo \
  --prompt "${PROMPT}" \
  || log "Gemini exited non-zero — checking for changes anyway"

git add -A
if git diff --cached --quiet && [ "$(git rev-list --count HEAD ^origin/${BASE_BRANCH} 2>/dev/null || echo 0)" = "0" ]; then
  log "no changes produced by Gemini — exiting cleanly without push"
  exit 0
fi

if ! git diff --cached --quiet; then
  git commit -m "${COMMIT_MESSAGE}" -m "Generated by GhostBot Gemini agent."
fi

log "pushing ${GH_BRANCH}..."
git push origin "${GH_BRANCH}"
log "done — branch ${GH_BRANCH} is on origin"
