#!/bin/bash
# GhostBot Codex CLI agent entrypoint.
#
# Required env:
#   GH_TOKEN         GitHub PAT
#   GH_REPO          owner/repo
#   GH_BRANCH        new branch
#   BASE_BRANCH      fork from (default: main)
#   PROMPT           user's request
#
# Either:
#   OPENAI_API_KEY   for real OpenAI
# Or:
#   OPENAI_BASE_URL  e.g. http://187.124.209.17:11434/v1 (Ollama compat)
#   OPENAI_API_KEY   any value for Ollama
#
# Optional:
#   MODEL            model name (default: gpt-5-codex for OpenAI)
#   COMMIT_MESSAGE   override commit message

set -euo pipefail

log() { echo "[codex-agent] $*"; }

require_env() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    log "ERROR: required env var $var is not set"
    exit 2
  fi
}

require_env GH_TOKEN
require_env GH_REPO
require_env GH_BRANCH
require_env PROMPT
require_env OPENAI_API_KEY

BASE_BRANCH="${BASE_BRANCH:-main}"
MODEL="${MODEL:-gpt-5-codex}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Agent: ${PROMPT:0:60}}"

REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${GH_REPO}.git"

log "repo=${GH_REPO} base=${BASE_BRANCH} branch=${GH_BRANCH} model=${MODEL}"

log "cloning..."
git clone --depth 50 --branch "${BASE_BRANCH}" "${REPO_URL}" /workspace/repo
cd /workspace/repo
git checkout -b "${GH_BRANCH}"

export OPENAI_API_KEY
[ -n "${OPENAI_BASE_URL:-}" ] && export OPENAI_BASE_URL

log "running Codex CLI..."
# codex exec = non-interactive, one-shot execution mode
codex exec \
  --model "${MODEL}" \
  --skip-git-repo-check \
  --dangerously-bypass-approvals-and-sandbox \
  "${PROMPT}" \
  || log "Codex exited non-zero — checking for changes anyway"

git add -A
if git diff --cached --quiet && [ "$(git rev-list --count HEAD ^origin/${BASE_BRANCH} 2>/dev/null || echo 0)" = "0" ]; then
  log "no changes produced by Codex — exiting cleanly without push"
  exit 0
fi

if ! git diff --cached --quiet; then
  git commit -m "${COMMIT_MESSAGE}" -m "Generated by GhostBot Codex agent."
fi

log "pushing ${GH_BRANCH}..."
git push origin "${GH_BRANCH}"
log "done — branch ${GH_BRANCH} is on origin"
