#!/bin/bash
# GhostBot OpenCode agent entrypoint.
# Reads config from environment variables, runs the full clone -> code -> push loop.
#
# Required env:
#   GH_TOKEN          GitHub Personal Access Token (Read+write Contents/PRs/Issues)
#   GH_REPO           owner/repo  (e.g. flndrnai/ghostbot)
#   GH_BRANCH         The new branch to push (e.g. agent-job/12345)
#   BASE_BRANCH       The branch to fork from (default: main)
#   PROMPT            The user's request, passed to OpenCode
#   OPENAI_BASE_URL   OpenAI-compatible endpoint (e.g. http://187.124.209.17:11434/v1)
#   OPENAI_API_KEY    Any value for Ollama (e.g. "ollama")
#   MODEL             Model name (e.g. qwen2.5-coder:7b)
#
# Optional:
#   COMMIT_MESSAGE    Override commit message (default: derived from prompt)

set -euo pipefail

log() {
  echo "[opencode-agent] $*"
}

require_env() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    log "ERROR: required env var $var is not set"
    exit 2
  fi
}

require_env GH_TOKEN
require_env GH_REPO
require_env GH_BRANCH
require_env PROMPT
require_env OPENAI_BASE_URL
require_env MODEL

BASE_BRANCH="${BASE_BRANCH:-main}"
OPENAI_API_KEY="${OPENAI_API_KEY:-ollama}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Agent: ${PROMPT:0:60}}"

REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${GH_REPO}.git"

log "repo=${GH_REPO} base=${BASE_BRANCH} branch=${GH_BRANCH}"
log "model=${MODEL} endpoint=${OPENAI_BASE_URL}"

# ============================================================
# 1. Clone
# ============================================================
log "cloning ${GH_REPO} (${BASE_BRANCH})..."
git clone --depth 50 --branch "${BASE_BRANCH}" "${REPO_URL}" /workspace/repo
cd /workspace/repo

git checkout -b "${GH_BRANCH}"
log "checked out new branch ${GH_BRANCH}"

# ============================================================
# 2. Configure OpenCode to use our LLM
# ============================================================
# OpenCode reads config from ~/.config/opencode/config.json or env vars.
# We use env vars so the image stays generic.
export OPENAI_BASE_URL
export OPENAI_API_KEY
export OPENCODE_MODEL="${MODEL}"

log "running OpenCode in headless mode..."
# OpenCode 'run' takes the prompt as a positional arg and uses
# provider/model format for -m. We pass openai/<model> so it
# routes through the OPENAI_BASE_URL we set above (Ollama).
opencode run -m "openai/${MODEL}" "${PROMPT}" || {
  log "OpenCode exited non-zero — capturing diff anyway"
}

# ============================================================
# 3. Stage + commit any changes
# ============================================================
git add -A
if git diff --cached --quiet; then
  log "no changes produced by OpenCode — exiting cleanly without push"
  exit 0
fi

log "committing..."
git commit -m "${COMMIT_MESSAGE}" -m "Generated by GhostBot OpenCode agent."

# ============================================================
# 4. Push
# ============================================================
log "pushing ${GH_BRANCH}..."
git push origin "${GH_BRANCH}"

log "done — branch ${GH_BRANCH} is on origin and ready for a PR"
