#!/bin/bash
# GhostBot Aider agent entrypoint.
#
# Required env:
#   GH_TOKEN          GitHub Personal Access Token
#   GH_REPO           owner/repo
#   GH_BRANCH         New branch to push (e.g. agent-job/12345)
#   BASE_BRANCH       Branch to fork from (default: main)
#   PROMPT            User's request, passed to Aider as --message
#   OLLAMA_BASE_URL   Ollama base URL WITHOUT /v1 (e.g. http://187.124.209.17:11434)
#   MODEL             Ollama model name (e.g. qwen2.5-coder:14b)
#
# Optional:
#   COMMIT_MESSAGE    Override commit message
#   AIDER_FILES       Space-separated list of files to add to Aider context
#                     (default: empty — Aider explores the repo itself)

set -euo pipefail

log() {
  echo "[aider-agent] $*"
}

require_env() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    log "ERROR: required env var $var is not set"
    exit 2
  fi
}

require_env GH_TOKEN
require_env GH_REPO
require_env GH_BRANCH
require_env PROMPT
require_env OLLAMA_BASE_URL
require_env MODEL

BASE_BRANCH="${BASE_BRANCH:-main}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Agent: ${PROMPT:0:60}}"
AIDER_FILES="${AIDER_FILES:-}"

REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${GH_REPO}.git"

log "repo=${GH_REPO} base=${BASE_BRANCH} branch=${GH_BRANCH}"
log "model=ollama/${MODEL} endpoint=${OLLAMA_BASE_URL}"

# ============================================================
# 1. Clone
# ============================================================
log "cloning ${GH_REPO} (${BASE_BRANCH})..."
git clone --depth 50 --branch "${BASE_BRANCH}" "${REPO_URL}" /workspace/repo
cd /workspace/repo
git checkout -b "${GH_BRANCH}"
log "checked out new branch ${GH_BRANCH}"

# ============================================================
# 2. Run Aider
# ============================================================
# Aider uses LiteLLM under the hood. For Ollama, it expects:
#   - model:    ollama/<model-name>
#   - env var:  OLLAMA_API_BASE  (NOT OLLAMA_BASE_URL)
export OLLAMA_API_BASE="${OLLAMA_BASE_URL}"

log "running Aider..."
# Flags:
#   --model              ollama/<name> routes via LiteLLM Ollama provider
#   --message            non-interactive prompt
#   --yes-always         don't prompt for confirmations
#   --no-show-model-warnings  silence the unknown-model startup nag
#   --no-stream          easier to capture full output
#   --auto-commits       Aider commits after a successful edit (default on)
#   --no-pretty          plain text output, easier to log
#   --no-check-update    don't phone home
#   --no-analytics       opt out of telemetry
#   --no-gitignore       don't auto-edit .gitignore
#   --map-tokens 0       skip repo map for fast smoke tests
if [ -n "${AIDER_FILES}" ]; then
  # shellcheck disable=SC2086
  aider \
    --model "ollama/${MODEL}" \
    --message "${PROMPT}" \
    --yes-always \
    --no-show-model-warnings \
    --no-stream \
    --no-pretty \
    --no-check-update \
    --no-analytics \
    --no-gitignore \
    --map-tokens 0 \
    ${AIDER_FILES} \
    || log "Aider exited non-zero — checking for changes anyway"
else
  aider \
    --model "ollama/${MODEL}" \
    --message "${PROMPT}" \
    --yes-always \
    --no-show-model-warnings \
    --no-stream \
    --no-pretty \
    --no-check-update \
    --no-analytics \
    --no-gitignore \
    --map-tokens 0 \
    || log "Aider exited non-zero — checking for changes anyway"
fi

# ============================================================
# 3. Aider auto-commits, but make sure everything is staged.
# ============================================================
git add -A
if git diff --cached --quiet && [ "$(git rev-list --count HEAD ^origin/${BASE_BRANCH} 2>/dev/null || echo 0)" = "0" ]; then
  log "no changes produced by Aider — exiting cleanly without push"
  exit 0
fi

# Stage anything Aider missed (rare)
if ! git diff --cached --quiet; then
  log "staging additional changes Aider didn't auto-commit..."
  git commit -m "${COMMIT_MESSAGE} (manual stage)" -m "Generated by GhostBot Aider agent."
fi

# ============================================================
# 4. Push
# ============================================================
log "pushing ${GH_BRANCH}..."
git push origin "${GH_BRANCH}"

log "done — branch ${GH_BRANCH} is on origin and ready for a PR"
